// Code generated by goctl. DO NOT EDIT.
package types

// LoginReq 登录请求结构体
// 包含电话号码和密码，用于身份验证
type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

// LoginResp 登录响应结构体
// 包含令牌、令牌过期时间和用户信息，用于身份验证和用户信息展示
type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
	User   User   `json:"user"`
}

// RegisterReq 注册请求结构体
// 包含电话号码、密码、昵称、性别和头像，用于新用户注册
type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Sex      byte   `json:"sex"`
	Avatar   string `json:"avatar"`
}

// RegisterResp 注册响应结构体
// 包含令牌和令牌过期时间，用于注册后的身份验证
type RegisterResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

// User 用户信息结构体
// 包含用户ID、电话号码、昵称、性别和头像，用于展示用户详细信息
type User struct {
	Id       string `json:"id"`
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Sex      byte   `json:"sex"`
	Avatar   string `json:"avatar"`
}

// UserInfoReq 用户信息请求结构体
// 为空，表示仅需用户身份验证即可获取信息
type UserInfoReq struct {
}

// UserInfoResp 用户信息响应结构体
// 包含用户详细信息，用于展示用户信息
type UserInfoResp struct {
	Info User `json:"info"`
}
